// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qute.Rfb.Api.Contexts;

#nullable disable

namespace Qute.Rfb.Api.Migrations
{
    [DbContext(typeof(RfbContext))]
    [Migration("20241205165043_Empresas")]
    partial class Empresas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Cnae", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("rfb_cnaes");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Empresa", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("id");

                    b.Property<decimal?>("CapitalSocial")
                        .HasColumnType("numeric")
                        .HasColumnName("capital_social");

                    b.Property<string>("EnteFederativo")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ente_federativo");

                    b.Property<string>("NaturezaJuridicaId")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("natureza_juridica_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<int?>("Porte")
                        .HasColumnType("integer")
                        .HasColumnName("porte");

                    b.Property<string>("QualificacaoId")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("qualificacao_id");

                    b.HasKey("Id");

                    b.HasIndex("NaturezaJuridicaId");

                    b.HasIndex("QualificacaoId");

                    b.ToTable("rfb_empresas");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Motivo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("rfb_motivos");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Municipio", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("rfb_municipios");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.NaturezaJuridica", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("rfb_naturezas_juridicas");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Pais", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("rfb_paises");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Qualificacao", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("rfb_qualificacoes");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Empresa", b =>
                {
                    b.HasOne("Qute.Rfb.Shared.Entities.NaturezaJuridica", "NaturezaJuridica")
                        .WithMany()
                        .HasForeignKey("NaturezaJuridicaId");

                    b.HasOne("Qute.Rfb.Shared.Entities.Qualificacao", "Qualificacao")
                        .WithMany()
                        .HasForeignKey("QualificacaoId");

                    b.Navigation("NaturezaJuridica");

                    b.Navigation("Qualificacao");
                });
#pragma warning restore 612, 618
        }
    }
}
