// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qute.Rfb.Api.Contexts;

#nullable disable

namespace Qute.Rfb.Api.Migrations
{
    [DbContext(typeof(RfbContext))]
    partial class RfbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Cnae", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("rfb_cnaes");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal?>("CapitalSocial")
                        .HasColumnType("numeric")
                        .HasColumnName("capital_social");

                    b.Property<string>("EnteFederativo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ente_federativo");

                    b.Property<string>("NaturezaJuridicaId")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("natureza_juridica_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<int?>("Porte")
                        .HasColumnType("integer")
                        .HasColumnName("porte");

                    b.Property<string>("QualificacaoId")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("qualificacao_id");

                    b.HasKey("Id");

                    b.ToTable("rfb_empresas");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.MeiSimples", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("MeiExclusao")
                        .HasColumnType("date")
                        .HasColumnName("mei_exclusao");

                    b.Property<DateOnly?>("MeiInclusao")
                        .HasColumnType("date")
                        .HasColumnName("mei_inclusao");

                    b.Property<bool?>("MeiOpcao")
                        .HasColumnType("boolean")
                        .HasColumnName("mei_opcao");

                    b.Property<DateOnly?>("SimplesExclusao")
                        .HasColumnType("date")
                        .HasColumnName("simples_exclusao");

                    b.Property<DateOnly?>("SimplesInclusao")
                        .HasColumnType("date")
                        .HasColumnName("simples_inclusao");

                    b.Property<bool?>("SimplesOpcao")
                        .HasColumnType("boolean")
                        .HasColumnName("simples_opcao");

                    b.HasKey("Id");

                    b.ToTable("rfb_simples");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Motivo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("rfb_motivos");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("rfb_municipios");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.NaturezaJuridica", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("rfb_naturezas_juridicas");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("rfb_paises");
                });

            modelBuilder.Entity("Qute.Rfb.Shared.Entities.Qualificacao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("rfb_qualificacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
